version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:                     
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - ./current/public:/usr/share/nginx/html

  sub-a:
    image: nginx:1.13.0-alpine
    container_name: con-a
    ports:
      - "8081:80"
    volumes:
      - ./web/a:/var/www/html/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: 'a.totsob.xyz'

  sub-b:
    image: nginx:1.13.0-alpine
    container_name: con-b
    ports:
      - "8082:80"
    volumes:
      - ./web/b:/var/www/html/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: 'b.totsob.xyz'

volumes:
  vhost:
networks:
  default:
    external:
      name: sandbox_network
